/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oop_final_project2;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 * Login Page GUI
 */
public class login_page extends javax.swing.JFrame {
    /**
     * Creates new form mainpage
     */
    public login_page() {
        initComponents();
        warning.setVisible(false);
        warning1.setVisible(false);
        warning2.setVisible(false);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        panel1 = new BackgroundPanel("/com/mycompany/oop_final_project2/resources/panterbg.jpg");
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        order = new javax.swing.JButton();
        bal1 = new javax.swing.JLabel();
        order1 = new javax.swing.JButton();
        bal3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        warning1 = new javax.swing.JLabel();
        warning2 = new javax.swing.JLabel();

        // Create a JLabel for the logo
        JLabel logoLabel = new JLabel();
        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/com/mycompany/oop_final_project2/resources/foodpanterlogo.png"));
        Image logoImage = logoIcon.getImage().getScaledInstance(350, 200, Image.SCALE_SMOOTH); // Resize the image to be bigger
        logoLabel.setIcon(new ImageIcon(logoImage));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(251, 111, 146));//pink border

        panel1.setForeground(new java.awt.Color(255, 204, 102));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 628, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login");

        jPanel1.setOpaque(false);
        jPanel1.setBackground(new java.awt.Color(251, 111, 146, 128)); // 128 is the alpha value for 50% opacity

        // Add the logo label to panel1
        panel1.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -30, 400, 250)); // x, y, width, height

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 115, 140, 60));//x, y, width, height

        warning.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 0, 0));
        warning.setText("Incorrect Password");
        panel1.add(warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        order.setBackground(new java.awt.Color(153, 102, 0));
        order.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        order.setForeground(new java.awt.Color(255, 255, 255));
        order.setText("Sign Up");
        order.setBorder(null);
        order.setFocusable(false);
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });
        panel1.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 120, 40));

        bal1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        bal1.setForeground(new java.awt.Color(255, 255, 255));
        bal1.setText("Password:  ");
        panel1.add(bal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        order1.setBackground(new java.awt.Color(153, 102, 0));
        order1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        order1.setForeground(new java.awt.Color(255, 255, 255));
        order1.setText("Login");
        order1.setBorder(null);
        order1.setFocusable(false);
        order1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order1ActionPerformed(evt);
            }
        });
        panel1.add(order1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 120, 40));

        bal3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        bal3.setForeground(new java.awt.Color(255, 255, 255));
        bal3.setText("Username: ");
        panel1.add(bal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        username.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        panel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 140, -1));
        panel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 140, -1));

        warning1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        warning1.setForeground(new java.awt.Color(255, 0, 0));
        warning1.setText("Enter Username and Password");
        panel1.add(warning1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        warning2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        warning2.setForeground(new java.awt.Color(255, 0, 0));
        warning2.setText("Account Does Not Exist");
        panel1.add(warning2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        signup_page sp = new signup_page();
        setVisible(false);
    }//GEN-LAST:event_orderActionPerformed

    private void order1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order1ActionPerformed
        String us = username.getText();
        String ps = String.valueOf(password.getPassword());
        new_account.users.forEach((username, password)->{
            if(username.equals(us)&&password.equals(ps)){
                new login(us,ps);
                setVisible(false);
            }
        });
        if(us.equals("")&&ps.equals("")){
            warning1.setVisible(true);
            Timer timer = new Timer(2000, e -> warning1.setVisible(false));
            timer.setRepeats(false);
            timer.start();
        }
        if(us.equals(account.test_account)){
            new login(us);
            setVisible(false);
        }
        else if(us.equals(account.username)&&ps.equals(account.password)){
            mainpage m = new mainpage();
            setVisible(false);
        }
        else if(us.equals(account.username)&&!ps.equals(account.password)){
            warning.setVisible(true);
            Timer timer = new Timer(2000, e -> warning.setVisible(false));
            timer.setRepeats(false);
            timer.start();
        }
        else if(!us.isBlank()&&!ps.isBlank()&&!us.equals(account.username)&&!ps.equals(account.password)){
            warning2.setVisible(true);
            Timer timer = new Timer(2000, e -> warning2.setVisible(false));
            timer.setRepeats(false);
            timer.start();
        }

    }//GEN-LAST:event_order1ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bal1;
    private javax.swing.JLabel bal3;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton order;
    private javax.swing.JButton order1;
    private BackgroundPanel panel1; // Use BackgroundPanel instead of java.awt.Panel
    private java.awt.Panel panel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    private javax.swing.JLabel warning;
    private javax.swing.JLabel warning1;
    private javax.swing.JLabel warning2;
    // End of variables declaration//GEN-END:variables
}
